//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace HCXT.Lib.BusinessService.WeixinReCallFileScaner.Service_MallService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MallServiceSoap", Namespace="http://tempuri.org/")]
    public partial class MallService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeamBykdinfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeamByCataIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBrandByCataIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateEBuayOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEBuayOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTeamOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeptIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBusiTypeByNatureOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebGridOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MallService() {
            this.Url = global::HCXT.Lib.BusinessService.WeixinReCallFileScaner.Properties.Settings.Default.HCXT_Lib_BusinessService_WeixinReCallFileScaner_Service_MallService_MallService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetTeamBykdinfoCompletedEventHandler GetTeamBykdinfoCompleted;
        
        /// <remarks/>
        public event GetTeamByCataIdCompletedEventHandler GetTeamByCataIdCompleted;
        
        /// <remarks/>
        public event GetBrandByCataIdCompletedEventHandler GetBrandByCataIdCompleted;
        
        /// <remarks/>
        public event CreateEBuayOrderCompletedEventHandler CreateEBuayOrderCompleted;
        
        /// <remarks/>
        public event UpdateEBuayOrderCompletedEventHandler UpdateEBuayOrderCompleted;
        
        /// <remarks/>
        public event CreateTeamOrderCompletedEventHandler CreateTeamOrderCompleted;
        
        /// <remarks/>
        public event GetDeptIdCompletedEventHandler GetDeptIdCompleted;
        
        /// <remarks/>
        public event CreateCaseCompletedEventHandler CreateCaseCompleted;
        
        /// <remarks/>
        public event GetBusiTypeByNatureCompletedEventHandler GetBusiTypeByNatureCompleted;
        
        /// <remarks/>
        public event GetWebGridCompletedEventHandler GetWebGridCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTeamBykdinfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTeamBykdinfo(string areacode, string casetype, string busitype) {
            object[] results = this.Invoke("GetTeamBykdinfo", new object[] {
                        areacode,
                        casetype,
                        busitype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTeamBykdinfoAsync(string areacode, string casetype, string busitype) {
            this.GetTeamBykdinfoAsync(areacode, casetype, busitype, null);
        }
        
        /// <remarks/>
        public void GetTeamBykdinfoAsync(string areacode, string casetype, string busitype, object userState) {
            if ((this.GetTeamBykdinfoOperationCompleted == null)) {
                this.GetTeamBykdinfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeamBykdinfoOperationCompleted);
            }
            this.InvokeAsync("GetTeamBykdinfo", new object[] {
                        areacode,
                        casetype,
                        busitype}, this.GetTeamBykdinfoOperationCompleted, userState);
        }
        
        private void OnGetTeamBykdinfoOperationCompleted(object arg) {
            if ((this.GetTeamBykdinfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeamBykdinfoCompleted(this, new GetTeamBykdinfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTeamByCataId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTeamByCataId(int cataid, int brandid) {
            object[] results = this.Invoke("GetTeamByCataId", new object[] {
                        cataid,
                        brandid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTeamByCataIdAsync(int cataid, int brandid) {
            this.GetTeamByCataIdAsync(cataid, brandid, null);
        }
        
        /// <remarks/>
        public void GetTeamByCataIdAsync(int cataid, int brandid, object userState) {
            if ((this.GetTeamByCataIdOperationCompleted == null)) {
                this.GetTeamByCataIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeamByCataIdOperationCompleted);
            }
            this.InvokeAsync("GetTeamByCataId", new object[] {
                        cataid,
                        brandid}, this.GetTeamByCataIdOperationCompleted, userState);
        }
        
        private void OnGetTeamByCataIdOperationCompleted(object arg) {
            if ((this.GetTeamByCataIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeamByCataIdCompleted(this, new GetTeamByCataIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBrandByCataId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBrandByCataId(int cataid) {
            object[] results = this.Invoke("GetBrandByCataId", new object[] {
                        cataid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBrandByCataIdAsync(int cataid) {
            this.GetBrandByCataIdAsync(cataid, null);
        }
        
        /// <remarks/>
        public void GetBrandByCataIdAsync(int cataid, object userState) {
            if ((this.GetBrandByCataIdOperationCompleted == null)) {
                this.GetBrandByCataIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBrandByCataIdOperationCompleted);
            }
            this.InvokeAsync("GetBrandByCataId", new object[] {
                        cataid}, this.GetBrandByCataIdOperationCompleted, userState);
        }
        
        private void OnGetBrandByCataIdOperationCompleted(object arg) {
            if ((this.GetBrandByCataIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBrandByCataIdCompleted(this, new GetBrandByCataIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateEBuayOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateEBuayOrder(string orderstruct) {
            object[] results = this.Invoke("CreateEBuayOrder", new object[] {
                        orderstruct});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateEBuayOrderAsync(string orderstruct) {
            this.CreateEBuayOrderAsync(orderstruct, null);
        }
        
        /// <remarks/>
        public void CreateEBuayOrderAsync(string orderstruct, object userState) {
            if ((this.CreateEBuayOrderOperationCompleted == null)) {
                this.CreateEBuayOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateEBuayOrderOperationCompleted);
            }
            this.InvokeAsync("CreateEBuayOrder", new object[] {
                        orderstruct}, this.CreateEBuayOrderOperationCompleted, userState);
        }
        
        private void OnCreateEBuayOrderOperationCompleted(object arg) {
            if ((this.CreateEBuayOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateEBuayOrderCompleted(this, new CreateEBuayOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateEBuayOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateEBuayOrder(string orderstruct) {
            object[] results = this.Invoke("UpdateEBuayOrder", new object[] {
                        orderstruct});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateEBuayOrderAsync(string orderstruct) {
            this.UpdateEBuayOrderAsync(orderstruct, null);
        }
        
        /// <remarks/>
        public void UpdateEBuayOrderAsync(string orderstruct, object userState) {
            if ((this.UpdateEBuayOrderOperationCompleted == null)) {
                this.UpdateEBuayOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEBuayOrderOperationCompleted);
            }
            this.InvokeAsync("UpdateEBuayOrder", new object[] {
                        orderstruct}, this.UpdateEBuayOrderOperationCompleted, userState);
        }
        
        private void OnUpdateEBuayOrderOperationCompleted(object arg) {
            if ((this.UpdateEBuayOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEBuayOrderCompleted(this, new UpdateEBuayOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateTeamOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateTeamOrder(string orderstruct) {
            object[] results = this.Invoke("CreateTeamOrder", new object[] {
                        orderstruct});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateTeamOrderAsync(string orderstruct) {
            this.CreateTeamOrderAsync(orderstruct, null);
        }
        
        /// <remarks/>
        public void CreateTeamOrderAsync(string orderstruct, object userState) {
            if ((this.CreateTeamOrderOperationCompleted == null)) {
                this.CreateTeamOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTeamOrderOperationCompleted);
            }
            this.InvokeAsync("CreateTeamOrder", new object[] {
                        orderstruct}, this.CreateTeamOrderOperationCompleted, userState);
        }
        
        private void OnCreateTeamOrderOperationCompleted(object arg) {
            if ((this.CreateTeamOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTeamOrderCompleted(this, new CreateTeamOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeptId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDeptId(string areacode) {
            object[] results = this.Invoke("GetDeptId", new object[] {
                        areacode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDeptIdAsync(string areacode) {
            this.GetDeptIdAsync(areacode, null);
        }
        
        /// <remarks/>
        public void GetDeptIdAsync(string areacode, object userState) {
            if ((this.GetDeptIdOperationCompleted == null)) {
                this.GetDeptIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeptIdOperationCompleted);
            }
            this.InvokeAsync("GetDeptId", new object[] {
                        areacode}, this.GetDeptIdOperationCompleted, userState);
        }
        
        private void OnGetDeptIdOperationCompleted(object arg) {
            if ((this.GetDeptIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeptIdCompleted(this, new GetDeptIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateCase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateCase(string areacode, string telphone, string linkman, string linkaddress, string casecontent, string casetype, string busitype) {
            object[] results = this.Invoke("CreateCase", new object[] {
                        areacode,
                        telphone,
                        linkman,
                        linkaddress,
                        casecontent,
                        casetype,
                        busitype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCaseAsync(string areacode, string telphone, string linkman, string linkaddress, string casecontent, string casetype, string busitype) {
            this.CreateCaseAsync(areacode, telphone, linkman, linkaddress, casecontent, casetype, busitype, null);
        }
        
        /// <remarks/>
        public void CreateCaseAsync(string areacode, string telphone, string linkman, string linkaddress, string casecontent, string casetype, string busitype, object userState) {
            if ((this.CreateCaseOperationCompleted == null)) {
                this.CreateCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCaseOperationCompleted);
            }
            this.InvokeAsync("CreateCase", new object[] {
                        areacode,
                        telphone,
                        linkman,
                        linkaddress,
                        casecontent,
                        casetype,
                        busitype}, this.CreateCaseOperationCompleted, userState);
        }
        
        private void OnCreateCaseOperationCompleted(object arg) {
            if ((this.CreateCaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCaseCompleted(this, new CreateCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBusiTypeByNature", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBusiTypeByNature(string casetype) {
            object[] results = this.Invoke("GetBusiTypeByNature", new object[] {
                        casetype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBusiTypeByNatureAsync(string casetype) {
            this.GetBusiTypeByNatureAsync(casetype, null);
        }
        
        /// <remarks/>
        public void GetBusiTypeByNatureAsync(string casetype, object userState) {
            if ((this.GetBusiTypeByNatureOperationCompleted == null)) {
                this.GetBusiTypeByNatureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBusiTypeByNatureOperationCompleted);
            }
            this.InvokeAsync("GetBusiTypeByNature", new object[] {
                        casetype}, this.GetBusiTypeByNatureOperationCompleted, userState);
        }
        
        private void OnGetBusiTypeByNatureOperationCompleted(object arg) {
            if ((this.GetBusiTypeByNatureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBusiTypeByNatureCompleted(this, new GetBusiTypeByNatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWebGrid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetWebGrid(string xmlparam) {
            object[] results = this.Invoke("GetWebGrid", new object[] {
                        xmlparam});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetWebGridAsync(string xmlparam) {
            this.GetWebGridAsync(xmlparam, null);
        }
        
        /// <remarks/>
        public void GetWebGridAsync(string xmlparam, object userState) {
            if ((this.GetWebGridOperationCompleted == null)) {
                this.GetWebGridOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebGridOperationCompleted);
            }
            this.InvokeAsync("GetWebGrid", new object[] {
                        xmlparam}, this.GetWebGridOperationCompleted, userState);
        }
        
        private void OnGetWebGridOperationCompleted(object arg) {
            if ((this.GetWebGridCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebGridCompleted(this, new GetWebGridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTeamBykdinfoCompletedEventHandler(object sender, GetTeamBykdinfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeamBykdinfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeamBykdinfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTeamByCataIdCompletedEventHandler(object sender, GetTeamByCataIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeamByCataIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeamByCataIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetBrandByCataIdCompletedEventHandler(object sender, GetBrandByCataIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBrandByCataIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBrandByCataIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateEBuayOrderCompletedEventHandler(object sender, CreateEBuayOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateEBuayOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateEBuayOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateEBuayOrderCompletedEventHandler(object sender, UpdateEBuayOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEBuayOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEBuayOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateTeamOrderCompletedEventHandler(object sender, CreateTeamOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateTeamOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateTeamOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDeptIdCompletedEventHandler(object sender, GetDeptIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeptIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeptIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateCaseCompletedEventHandler(object sender, CreateCaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetBusiTypeByNatureCompletedEventHandler(object sender, GetBusiTypeByNatureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBusiTypeByNatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBusiTypeByNatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetWebGridCompletedEventHandler(object sender, GetWebGridCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebGridCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebGridCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591